export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';

export const SET_ALERTS = 'SET_ALERTS';
export const SET_MUTATE_ALERTS = 'SET_MUTATE_ALERTS';
export const SET_FILTERED_ALERTS = 'SET_FILTERED_ALERTS';
export const SET_CLEAR_ALERTS = 'SET_CLEAR_ALERTS';

export const SET_SETTINGS = 'SET_SETTINGS';
